Resources:
  DynamoCareTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: CareId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: CareId
          KeyType: HASH
      TableName: ${env:MEDFORM_TABLE_NAME}
