Resources:
  DnsRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Comment: 'CloudFront alias record for ${env:MEDFORM_DOMAIN_NAME}'
      HostedZoneId: '${env:MEDFORM_DOMAIN_HOSTED_ZONE_ID}'
      Type: A
      Name: '${env:MEDFORM_DOMAIN_NAME}'
      AliasTarget:
        DNSName: !GetAtt CFDistribution.DomainName
        HostedZoneId: 'Z2FDTNDATAQYW2'
